print("applying general settings... ")
cmd.bg_color("white")
cmd.set('fog', '0')
cmd.set('orthoscopic', 0)
cmd.set("ray_opaque_background", 1)
cmd.set("cartoon_side_chain_helper", 1)
cmd.set("cartoon_round_helices", 0)
cmd.set("ray_shadow", 0)
cmd.set('ray_trace_fog', 0)
cmd.set("ray_trace_mode", 1)
cmd.set("ray_trace_gain", 0)
cmd.set("ray_texture", 0)
cmd.set('hash_max', 300)
cmd.set('antialias', 2)
cmd.set('surface_quality', 0)
#cmd.set('surface_quality', 4)
cmd.set_bond("stick_radius", .2, 'all')
cmd.set('stick_ball', 1)  
cmd.set('stick_ball_ratio', 1.3)
cmd.set('surface_smooth_edges', 1)
cmd.set('surface_proximity', 0)
cmd.set("dash_gap", 0.4)
cmd.set("dash_length", 0.001)
cmd.set("dash_width", 3)
cmd.valence("guess", "all")
cmd.set("light_count",1)
cmd.set("ambient", 0.5)
cmd.set("direct", 0.1)
cmd.set("reflect", 0.5)
cmd.set("specular", 0)
